apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
images:
- name: quay.io/cmays20/hello-world
  newTag: 0729a07f40f0d05ddc54e54a9d4a67b4ac9059e0
configMapGenerator:
- literals:
  - app=hello-world-dev
  name: environment-variables
