apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
images:
- name: quay.io/cmays20/hello-world
  newTag: ef9534af2f835d67752b5de9c29b17e7da434b17
configMapGenerator:
- literals:
  - app=hello-world-dev
  name: environment-variables
