apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
images:
- name: quay.io/cmays20/hello-world
  newTag: 5829208e5edccc9c3106ef1a94f8f970123f05cd
configMapGenerator:
- literals:
  - app=hello-world-dev
  name: environment-variables
