apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
images:
- name: quay.io/cmays20/hello-world
  newTag: 6e4a2dfb3ee7045457e7f99996e1b2e505e0504d
configMapGenerator:
- literals:
  - app=hello-world-dev
  name: environment-variables
